### PR TITLE
Issue #997: Add new listing for homepage

### LINKED ISSUE #997: Add new "/" listing page to test fixture catalog.xml
When the catalog.xml fixture file is used to test out L&P it would be helpful if it included data for a homepage. That way the person trying it out would not get to see 404 as the first thing.

### PR DESCRIPTION
**Pull request by Schrank**
Test tests will fail, to succeed, we first need to merge https://github.com/lizards-and-pumpkins/catalog/pull/1082

Fixes #997

### CODE REVIEW

**Comment by tim-bezhashvyly** [comment]
#1082 is merged. Please rebase.

**Comment by tim-bezhashvyly** [comment]
Could you please also fix this bug introduced by #1082?

https://scrutinizer-ci.com/g/lizards-and-pumpkins/catalog/inspections/113083ba-d801-43a3-9a29-0660198cc1a6/issues/files/src/DataPool/UrlKeyStore/InMemoryUrlKeyStore.php?status=new&orderField=path&order=asc&honorSelectedPaths=0

**Comment by Schrank** [comment]
@tim-bezhashvyly Bug fixed and rebased.

**Comment by Schrank** [comment]
Searching the bug.

**Comment by Schrank** [comment]
We should merge https://github.com/lizards-and-pumpkins/catalog/issues/1085 before and make sure, the test is green :)

**Comment by tim-bezhashvyly** [comment]
Blocked by #1086.

**Pull request merged**
